name: Axe accessibility testing

on:
  # Enabled accessibility testing on every push and PR
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/**.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - ".github/scripts/prepare-jekyll-build-env.sh"
      - ".github/workflows/axe.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/**.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - ".github/scripts/prepare-jekyll-build-env.sh"
      - ".github/workflows/axe.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  workflow_dispatch:
    inputs:
      url:
        description: "URL to be checked (e.g.: blog/)"
        required: false

env:
  URL: ""

concurrency:
  group: axe-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          changes: |
            {
              "giscus.repo": "${{ github.repository }}",
              "baseurl": ""
            }
      - name: Install and Build 🔧
        run: |
          bash .github/scripts/prepare-jekyll-build-env.sh
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Setup Chrome 🌐
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true
      - name: Run axe 🪓
        # https://github.com/dequelabs/axe-core-npm/tree/develop/packages/cli
        continue-on-error: true
        run: |
          npm install -g @axe-core/cli
          npm install -g http-server
          http-server _site/ &
          axe --chromedriver-path "${{ steps.setup-chrome.outputs.chromedriver-path }}" http://localhost:8080/${{ github.event.inputs.url || env.URL }} --load-delay=1500 --exit || true
